# Example GitLab CI Configuration - BOM SCA Scanning

include:
  - local: 'ci-templates/gitlab-ci/bom-sca-scan.yml'

stages:
  - test

variables:
  SCA_BOM_DETECT_DOWNLOAD_URL: "https://download.scantist.io/sca-bom-detect.jar"
  DEVSECOPS_TOKEN: "${DEVSECOPS_TOKEN}"
  DEVSECOPS_IMPORT_URL: "${DEVSECOPS_IMPORT_URL}"
