version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - orb-tools/publish:
          orb-name: scan/sca
          vcs-type: << pipeline.project.type >>
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - shellcheck/check
            - orb-tools/review
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
